version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
      - build
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      steps:
        - checkout
        - run: npm run-script build
